  openvpn-admin:
    image: flant/openvpn-admin
    container_name: openvpn_admin
    restart: always
    networks:
      - openvpn-net
    ports:
      - "8080:8080"  # Web UI Port
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=adminpassword
      - OVPN_SERVER=openvpn_server:5555  # Connect to OpenVPN Management Interface
    volumes:
      - ./openvpn-data:/etc/openvpn
      
# networks:
#   openvpn-net:
#     external: true
